version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    image: willinha-rails
    user: root
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: bash ./scripts/entrypoint.sh
